# Nom de l'application
spring.application.name=quizify

# ===============================
# CONFIG POSTGRESQL (RENDER)
# ===============================

spring.datasource.url=jdbc:postgresql://dpg-d7j6577aqgkc73ac9jeg-a.oregon-postgres.render.com:5432/quizify_db_htu0
spring.datasource.username=root
spring.datasource.password=Nk5fAKT48WqGZmnG5uAQItV9TacUhYQl
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# PORT RENDER (OBLIGATOIRE)
# ===============================

server.port=${PORT:8080}

# --- DÉSACTIVER LA SÉCURITÉ ---
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# --- CONFIGURATION EMAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moxekeep@gmail.com
spring.mail.password=dxhh lywz uuez xosr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true